version: '2'
services:
  web:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./public:/public
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
  php:
    container_name: php
    build: ./docker/php
    volumes:
      - ./public:/public
      - ./vendor:/www/vendor
      - ./src:/www/src
      - ./composer.json:/www/composer.json
    environment:
      - VENDOR_PATH=/www/vendor/
    env_file:
      - .env
